const PDFDocument = require("pdfkit");

const formatDateToYYYYMMDD = (date) => {
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
};

const formatReadableDate = (date) => {
  return date.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
};

const parseLocalDate = (dateStr) => {
  const [year, month, day] = dateStr.split("-").map(Number);
  return new Date(year, month - 1, day);
};

const moodMap = {
  "Low": 1,
  "Okay": 2,
  "Good": 3,
  "Great": 4,
  "Amazing": 5,
};

const labelMap = {
  1: "Low",
  2: "Okay",
  3: "Good",
  4: "Great",
  5: "Amazing",
};

exports.generateReport = async (req, res) => {
  try {
    const { range, moods, journals, gratitude, streak } = req.body;

    const today = new Date();
    const start = new Date(today);
    if (range === "weekly") {
      start.setDate(today.getDate() - 6);
    } else {
      start.setDate(today.getDate() - 29);
    }

    const todayString = formatDateToYYYYMMDD(today);
    const startString = formatDateToYYYYMMDD(start);

    const filteredMoods = (moods || []).filter(
      (entry) => entry.date >= startString && entry.date <= todayString
    );
    const filteredJournals = (journals || []).filter(
      (entry) => entry.date >= startString && entry.date <= todayString
    );
    const filteredGratitude = (gratitude || []).filter(
      (entry) => entry.date >= startString && entry.date <= todayString
    );

    const totalMoods = filteredMoods.length;
    const totalJournals = filteredJournals.length;
    const totalGratitude = filteredGratitude.length;

    let avgMoodLabel = "No data";
    if (totalMoods > 0) {
      const sum = filteredMoods.reduce(
        (acc, entry) => acc + (moodMap[entry.mood] || 0),
        0
      );
      const avg = Math.round(sum / totalMoods);
      avgMoodLabel = labelMap[avg] || "No data";
    }

    const reportTitle =
      range === "weekly" ? "Weekly Wellness Report" : "Monthly Wellness Report";
    const dateRangeLabel = `${formatReadableDate(start)} – ${formatReadableDate(
      today
    )}`;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      'attachment; filename="serene-report.pdf"'
    );

    const doc = new PDFDocument({ margin: 50 });

    doc.on("pageAdded", () => {
      const savedY = doc.y;
      const savedX = doc.x;
      const savedBottom = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      doc
        .fontSize(9)
        .fillColor("#8C7E6A")
        .font("Helvetica")
        .text(
          "Generated by Serene • Your calm space",
          50,
          doc.page.height - 40
        );
      doc.page.margins.bottom = savedBottom;
      doc.y = savedY;
      doc.x = savedX;
    });

    // Manually add footer to the first page
    const savedY = doc.y;
    const savedX = doc.x;
    const savedBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc
      .fontSize(9)
      .fillColor("#8C7E6A")
      .font("Helvetica")
      .text("Generated by Serene • Your calm space", 50, doc.page.height - 40);
    doc.page.margins.bottom = savedBottom;
    doc.y = savedY;
    doc.x = savedX;

    doc.pipe(res);

    // PDF Header section
    doc.fontSize(24).fillColor("#4A7C59").font("Helvetica").text("🌿 Serene");
    doc.y += 4;

    doc.fontSize(18).fillColor("#2C2416").font("Helvetica-Bold").text(reportTitle);
    doc.y += 4;

    doc.fontSize(11).fillColor("#8C7E6A").font("Helvetica").text(dateRangeLabel);
    doc.y += 4;

    doc
      .fontSize(10)
      .fillColor("#8C7E6A")
      .font("Helvetica")
      .text("Generated on " + formatReadableDate(today));

    doc
      .moveTo(50, doc.y + 10)
      .lineTo(545, doc.y + 10)
      .strokeColor("#D4CDB8")
      .stroke();
    doc.y += 20;

    // Section 1 — Stats Overview
    doc.fontSize(14).fillColor("#2C2416").font("Helvetica-Bold").text("Overview");
    doc.y += 8;

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#D4CDB8").stroke();
    doc.y += 10; // Standard spacing after drawing line

    doc.fontSize(12).fillColor("#2C2416").font("Helvetica").text("Active Streak: " + streak + " days");
    doc.y += 6;

    doc.text("Mood check-ins: " + totalMoods);
    doc.y += 6;

    doc.text("Journal entries: " + totalJournals);
    doc.y += 6;

    doc.text("Gratitude logs: " + totalGratitude);
    doc.y += 6;

    doc.text("Average mood: " + avgMoodLabel);
    doc.y += 16;

    // Section 2 — Mood Summary
    doc.fontSize(14).fillColor("#2C2416").font("Helvetica-Bold").text("Mood Log");
    doc.y += 8;

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#D4CDB8").stroke();
    doc.y += 10; // Standard spacing after drawing line

    if (totalMoods === 0) {
      doc
        .fontSize(11)
        .fillColor("#8C7E6A")
        .font("Helvetica")
        .text("No mood entries for this period.");
      doc.y += 16;
    } else {
      const sortedMoods = [...filteredMoods].sort((a, b) =>
        a.date.localeCompare(b.date)
      );
      for (const entry of sortedMoods) {
        const moodNum = moodMap[entry.mood] || 1;
        const entryDate = parseLocalDate(entry.date);
        const readableDate = formatReadableDate(entryDate);

        doc
          .fontSize(11)
          .fillColor("#2C2416")
          .font("Helvetica")
          .text(readableDate + "  →  " + entry.mood + "  ", {
            continued: true,
          });

        doc
          .fontSize(10)
          .fillColor("#4A7C59")
          .font("Helvetica")
          .text("█".repeat(moodNum));
        
        doc.y += 5;
      }
      doc.y += 16;
    }

    // Section 3 — Journal Entries
    doc
      .fontSize(14)
      .fillColor("#2C2416")
      .font("Helvetica-Bold")
      .text("Journal Entries");
    doc.y += 8;

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#D4CDB8").stroke();
    doc.y += 10; // Standard spacing after drawing line

    if (totalJournals === 0) {
      doc
        .fontSize(11)
        .fillColor("#8C7E6A")
        .font("Helvetica")
        .text("No journal entries for this period.");
      doc.y += 20;
    } else {
      const sortedJournals = [...filteredJournals].sort((a, b) =>
        b.date.localeCompare(a.date)
      );
      for (const entry of sortedJournals) {
        if (doc.page.height - doc.y - 50 < 100) {
          doc.addPage();
        }

        doc
          .fontSize(13)
          .fillColor("#2C2416")
          .font("Helvetica-Bold")
          .text(entry.title);
        doc.y += 4;

        const entryDate = parseLocalDate(entry.date);
        const readableDate = formatReadableDate(entryDate);
        doc
          .fontSize(10)
          .fillColor("#8C7E6A")
          .font("Helvetica")
          .text(readableDate);
        doc.y += 6;

        doc
          .fontSize(11)
          .fillColor("#2C2416")
          .font("Helvetica")
          .text(entry.body, { lineGap: 5.5 });
        doc.y += 12;

        doc
          .moveTo(50, doc.y)
          .lineTo(545, doc.y)
          .strokeColor("#D4CDB8")
          .lineWidth(0.5)
          .stroke();
        doc.lineWidth(1); // Reset global line width back to default
        doc.y += 10; // Standard spacing after drawing line
      }
      doc.y += 20;
    }

    // Section 4 — Gratitude Highlights
    doc
      .fontSize(14)
      .fillColor("#2C2416")
      .font("Helvetica-Bold")
      .text("Gratitude Highlights");
    doc.y += 8;

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#D4CDB8").stroke();
    doc.y += 10; // Standard spacing after drawing line

    if (totalGratitude === 0) {
      doc
        .fontSize(11)
        .fillColor("#8C7E6A")
        .font("Helvetica")
        .text("No gratitude entries for this period.");
    } else {
      const sortedGratitude = [...filteredGratitude].sort((a, b) =>
        b.date.localeCompare(a.date)
      );
      for (const entry of sortedGratitude) {
        if (doc.page.height - doc.y - 50 < 80) {
          doc.addPage();
        }

        const entryDate = parseLocalDate(entry.date);
        const readableDate = formatReadableDate(entryDate);
        doc
          .fontSize(12)
          .fillColor("#2C2416")
          .font("Helvetica-Bold")
          .text(readableDate);
        doc.y += 6;

        for (const item of entry.items || []) {
          if (item && item.trim()) {
            doc
              .fontSize(11)
              .fillColor("#2C2416")
              .font("Helvetica")
              .text("  • " + item);
            doc.y += 5;
          }
        }
        doc.y += 10;
      }
    }

    doc.end();
  } catch (error) {
    console.error("PDF Generation error:", error);
    if (!res.headersSent) {
      res.status(500).json({ error: "Failed to generate PDF report" });
    }
  }
};
